### ISSUE TITLE
[BUG] Empty key in YAML sets value to null

### ISSUE THREAD

**Issue by ddbtrmatic** [node-config/node-config#751]
**Describe the bug**

Merging two YAML config files results in a null value if the last file has an empty key.

Example:

```yml
# default.yml

db:
  global:
    host: something
    options:
      useUTC: true

```

```yml
# development.yml

db:
  global:
    host: something_else
    # options key left blank
    options:
```

Result:

```js
{
  db: {
    global: {
      host: 'something_else',
      options: null
    }
  }
}
```

**Expected behavior**
I would intuitively expect that the empty key is treated the same as an empty object in JSON and merged.

### Please tell us about your environment:

 -  node-config version: 3.3.7
 -  node-version: 18.18.0
